# -*- coding: utf-8 -*-
{
    'name': "Construction Management Indonesia",

    'summary': "Addon Manajemen Konstruksi yang bisa diterapkan di Indonesia mencakup pekerjaan perencanaan, pelaksanaan, dan pemeliharaan",

    'author': "PT Fujicon Priangan Perdana",
    'website': "https://erp.fujicon-japan.com/",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/15.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Services',
    # 'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': ['base','hr','contacts','project','stock', 'sale_management', 'hr_attendance',
                'web', 'base_setup', 'web_editor', 'product', 'purchase', 'sale_project', 'sale_management'],
    'assets': {
        'web.assets_backend': [
            'https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js',
            'https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0',
            'fits_management_construction/static/src/js/library.js',
            'fits_management_construction/static/src/xml/fits_project_curve_s_templates.xml',
            'fits_management_construction/static/src/js/curve_s_chart.js',
        ],
        'web.assets_frontend': [
            "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css",
        ],
        # 'web_editor.backend_assets_wysiwyg': [
        #     'fits_management_construction/static/src/js/wysiwyg/**/*',
        #     'https://cdn.jsdelivr.net/npm/showdown/dist/showdown.js'
        # ],
        # 'web_editor.assets_wysiwyg': [
        #     'fits_management_construction/static/lib/showdown.js',
        # ]
    },

    # always loaded
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence_no_mitigation.xml',
        'data/sequence_no_hse.xml',
        'data/sequence_no_stakeholder.xml',
        'data/sequence_no_upd.xml',
        'data/sequence_no_ahs.xml',
        'data/sequence_no_boq.xml',
        'data/sequence_no_rab.xml',
        'data/sequence_no_document_report.xml',
        'data/sequence_no_daily_report.xml',
        'data/sequence_no_foundry_permits.xml',
        'data/sequence_no_work_request.xml',
        'data/sequence_no_meeting.xml',
        'data/sequence_no_nonconformance_report_form.xml',
        'data/sequence_no_doc_inoutbond.xml',
        'data/masterdata/field_condition_data.xml',
        'data/masterdata/impact_data.xml',
        'data/masterdata/likelihood_data.xml',
        'data/masterdata/risk_mitigation_type_data.xml',
        'data/masterdata/risk_scale_data.xml',
        'data/masterdata/location_data.xml',
        # 'data/masterdata/res_user_data.xml',
        'reports/report_risk_mitigation_template.xml',
        'reports/report_stakeholder_analysis_template.xml',
        'reports/report_health_safety_environment_template.xml',
        'reports/report_ahs_template.xml',
        'reports/report_daily_report_template.xml',
        'reports/report_boq_template.xml',
        'reports/report_rab_template.xml',
        'reports/report_rab_recap_template.xml',
        'reports/report_defect_list_template.xml',
        'reports/report_overtime_permission_template.xml',
        'reports/report_execution_permits_template.xml',
        'reports/report_foundry_permits_template.xml',
        'reports/report_work_request_template.xml',
        'reports/report_goods_submission_template.xml',
        'reports/report_nonconformance_report_form_template.xml',
        'reports/report_doc_inoutbond_template.xml',
        'reports/report_feasibility_inspection_template.xml',
        'reports/report_work_correction_template.xml',
        'reports/report_working_drawing_template.xml',
        'reports/report_field_change_template.xml',
        'reports/report_implementation_permits_template.xml',
        'reports/report_material_approval_template.xml',
        'reports/report_supervision_form_template.xml',
        'reports/report_weather_monitoring_template.xml',
        'reports/report_final_submission_template.xml',
        # 'reports/report_bills_of_materials.xml',
        'views/fits_management_construction_menu_views.xml',
        'views/fits_analysis_risk_mitigation_views.xml',
        'views/fits_health_safety_environment_views.xml',
        'views/fits_budget_plan_rab_views.xml',
        'views/fits_bill_of_quantity_rab_views.xml',
        'views/fits_unit_price_analysis_rab_views.xml',
        'views/fits_unit_price_data_rab_views.xml',
        'views/fits_inherit_product_template_rab_views.xml',
        'views/fits_configuration_views.xml',
        'views/fits_stakeholder_analysis_views.xml',
        'views/fits_daily_report_views.xml',
        'views/fits_document_report_views.xml',
        'views/fits_inherit_project_project_views.xml',
        'views/fits_inherit_project_manpower_absensi_views.xml',
        'views/fits_inherit_rfq_views.xml',
        'views/fits_inherit_resconfig_setting_views.xml',
        # 'views/fits_inherit_project_template_absensi_views.xml',
        'views/fits_inherit_attendances_template_views.xml',
        'views/fits_inherit_hr_employee_views.xml',
        'views/fits_inherit_sale_order_views.xml',
        'views/fits_inherit_project_task_views.xml',
        'views/fits_inherit_document_layout_views.xml',
        'views/fits_defect_list_form_views.xml',
        'views/fits_overtime_permission_form_views.xml',
        'views/fits_execution_permits_form_views.xml',
        'views/fits_foundry_permits_views.xml',
        'views/fits_work_request_views.xml',
        'views/fits_goods_submission_form_views.xml',
        'views/fits_nonconformance_report_form_views.xml',
        'views/fits_project_curve_s_views.xml',
        # 'views/fits_project_curve_s_templates.xml',
        # 'static/src/xml/fits_project_curve_s_templates.xml',
        # 'views/assets.xml',
        # 'views/fits_project_curve_s_tgitemplates.xml',
        'views/fits_document_inoutbond_views.xml',
        'views/fits_feasibility_inspection_document_views.xml',
        'views/fits_work_correction_views.xml',
        'views/fits_working_draw_approval_views.xml',
        'views/fits_field_change_views.xml',
        'views/fits_implementation_permits_views.xml',
        'views/fits_material_approval_form_views.xml',
        'views/fits_supervision_views.xml',
        'views/fits_weather_monitoring_views.xml',
        'views/fits_final_submission_views.xml',
        # 'views/fits_inherit_res_user_views.xml',
        # 'views/fits_bills_of_materials_views.xml',
    ],
    'controllers': [ 
        'controllers/unit_price_data_api.py',
        'controllers/fits_project_curve_s_controller.py',
        'controllers/fits_daily_report_pdf.py'
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': True,
}